### ISSUE TITLE
Some servo outputs are on 100% even with position set to 0

### ISSUE THREAD

**Issue by Hardbaer** [Tinkerforge/servo-brick#2]
I am using Brick-Viewer 2.4.9 to control a Servo-brick. It does not matter if it is attached directly or via a RED-brick.
All Servo-outputs are configured as displayed in the screenshot.

![Bug_Servo-Brick](https://user-images.githubusercontent.com/18546391/69422660-7ae47e00-0d24-11ea-98d2-80c1890f5eac.png)

When enabling servo 2,5 or 6 the corresponding output goes to high although the position was set to 0. All other outputs work as expected. 
When increasing the position from 0 to 9 nothing changes on the mentioned output. From position 10 on the output works as expected. This means it generates the according pwm-signal.

**Comment by borg42** [comment]
Channels 0, 1, 3 and 4 use PWM hardware units of the microcontroller, while channels 2, 5 and 6 use Timer/Counter (there are only 4 PWM hardware units available).

I haven't looked at the datasheet yet, but the TC hardware unit probably has a little bit less resolution, so that explains why it can't generate the tiny period you are configuring with positions smaller 10.

The other problem is that when the PWM should be turned off the signal is high for channels 2, 5, and 6? Did i understand that correctly?

**Comment by Hardbaer** [comment]
Neither the resolution nor that nothing changes until position 10 is a problem for me.
The problem I have experienced is that the output is high when it  should be low according to the position setting. So yes, you did get it correctly.

**Comment by Hardbaer** [comment]
Sorry. Wrong button.

**Comment by Hardbaer** [comment]
Some further investigations showed that you can improve that behaviour with increasing the pulse width an the period. This results in reducing the position value when it starts to function correctly to at least 1.
But when setting it to 0 it jumps back to high level.

**Comment by borg42** [comment]
I took a look at the datasheet and the Timer/Counter does not support "counting to 0". So i added some extra handling for the case that the min pulse width and position is set to 0.

Can you test the attached firmware? Does it solve your problem?

[servo-brick-test-2.3.9.zip](https://github.com/Tinkerforge/servo-brick/files/3879950/servo-brick-test-2.3.9.zip)

**Comment by Hardbaer** [comment]
The firmware now works as expected. My problem is solved. Fast and precise as I know it from Tinkerforge. Thank you. Have a nice weekend.

**Comment by borg42** [comment]
Changes are commited (https://github.com/Tinkerforge/servo-brick/commit/ad70b6a71eca45b4772f3a142ba019abe55b1676) and firmware version 2.3.9 is released.
